version: "3"

services:
  postgres:
    image: "postgres:16.4-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "jitsi"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:7.2.5"

volumes:
  postgres_data:
